<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\src\NexArc.Authentication.Client\NexArc.Authentication.Client.csproj" />
    <ProjectReference Include="..\..\src\NexArc.Authentication.Provider.Auth0B2C\NexArc.Authentication.Provider.Auth0B2C.csproj" />
    <ProjectReference Include="..\Examples.ServiceDefaults\Examples.ServiceDefaults.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
